name: safety_guard
description: 안전지키미 – 엽사 근접 경보 앱
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^14.0.2
  http: ^1.2.0
  device_info_plus: ^12.2.0
  vibration: ^3.1.4
  just_audio: ^0.10.5
  characters: ^1.4.0
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  flutter_tts: ^3.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/mp3/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"   # 필요 시 변경 가능
  adaptive_icon_foreground: "assets/icon/app_icon.png"