name: safety_guard
description: 안전지키미 – 엽사 근접 경보 앱
publish_to: "none"
version: 1.0.0+12

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^13.0.1
  http: ^1.2.0
  device_info_plus: ^10.1.2
  vibration: ^2.0.1
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.10
  characters: ^1.3.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  flutter_tts: ^3.8.0
  focus_detector: ^2.0.1
  background_fetch: ^1.3.5

  # ✅ package_info_plus 최신버전 (FFI 충돌 해결)
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/mp3/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"   # 필요 시 변경 가능
  adaptive_icon_foreground: "assets/icon/app_icon.png"
